[package]
name = "rudoku"
version = "0.1.0"
authors = ["Jan Miderbäck <jan.miderback@qlik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
